sudo: required

env:
  - CXX="g++-4.8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

language: node_js

node_js:
  - 8

before_script:
  - npm install eslint-config-medopad --no-save

deploy:
  provider: npm
  email: j.osokinas@gmail.com
  api_key:
    secure: 3Db8hp6imS/QnDs3EbOO7vUTMMe8O9z/bLN59acK9lwGsfB3I07nBuyvZHDz5x2it33MUKX8e9XLOPMQD+CoVA4XrzdRX4qdkrLn71iiDbV2eVPtJqUgachxAvskMZsNczM0n4EZg3xKT4I2lOajHL9bZ311pwGFLFDkOwVFOAirzMaCq3tWVySWTk9pAnDsfqm2Fbi5dnxoIVmrwAdb8QvXn9vmeIO0sGqJiP0QJuoJODFnSjBIwu9Fq84z9E+I2E0tVcQ9+jElnPDBiZoDSfbnGgmu1F6rSrqOY+0nTLqtUl+y7DrYkcEUCG5OolHbYehJbQG7gRCsAz+GotkmG2Xe6ghqUeM94HsPlBlwFgRKFNlbi2wx5FmLzCK3L2xBwnIMvfBTwKHfPlb3Kxpi9XPRBGcxIg5StGdevLN9Wkr7bFUJZ6O9dvZ3+u6rk9rC56BGD5aWUlxIBH1QZQMv0yDS+oXYkQtcHu07sBkpIlo29ddLWbPu1ZEWw1cNfnF3g6le3wMT8mHs5OCp2deGYDOSIV9QPMGsxChyTeeD9TFK+qDMrSW8J0RhJiz77taS/NvVv9qn+4EjyccbAiOXhss8qLcRysHEXJTJRG7YbFcjXqAQyniGg/u7bftAG9LpXQGp0imFe8TBXhvUXl1079PRLa8xTAt/vAtt/0Xdfhs=
  on:
    tags: true
    branch: master
