dist: trusty
sudo: required

env:
  - CXX="g++-4.8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

language: node_js

node_js:
  - 5
  - 6
  - 7

before_script:
  - npm install eslint-config-medopad
