env:
  - CXX="g++-4.8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

language: node_js

node_js:
  - 8

before_script:
  - npm install eslint-config-medopad --no-save

deploy:
  provider: npm
  email: bobby.biran@medopad.com
  api_key:
    secure: Fk6pUvLoRzZJGHzv0DsqnXtG8YGoohSgKBTRaWjA3TAF96EI+ZTy+te3UdJAqaXUIU0SbL2VZ/xS9/6CWzWy/idjbFxrizFltfDm71zua41resSZJ5Lc1kTu+FWlFvnfRm47iE5KF9szO/sWOr52lobAhdUIw30fzNCtmT7tjR3tKksf+8BB+kvQdUhfnTEOu8fqYelcXTArxif3t3qrvz/Dz64WkABpIWbLx3CnQ4rcPGqdCpbMVolhGR0jDEoHFEXYFeMXRMehr8/3bFbvvjYlz5t7S9Koi63O8ZgVf6cS51E+aFtBEHycWGODNg0QGHO5iTy84sL/h6yO/sKcl0hoDTXS+2R5qFSh65lSXB0fBoy1bBjv59YNpZs1KUwSafQ3O+nqRoWwEUFST7Nu1DV+L8arIPPveJXrwR/2dwb/4L9DAFwG/8U4QBbI+0YkxRI+oDHBqbFYeKKgr81xLK00GAsegFrV1fuOGITNEe2iKPMVU3iu0Xmagoah3WOjgSjI2QsxvFWtobc0MuiMQnzUvfeO9Rf2ANm4OglL9rHiXiip3U+b9oXJryvRhs5mKCBmavsSNDzG81IGbtu4oFVfP3F1p6dWvHO1y/d63zWNkOJ29vYx/WuMhFPJS/a5i4BhpOyZ/2qIja2w975WeIRtce70X+PpyejSxekCQp8=
  on:
    tags: true
    repo: Medopad/eslint-config-medopad-react
